sudo: required
language: java
jdk:
  - oraclejdk7
  - oraclejdk8
before_install:
  - sudo pip install codecov
after_success:
  - codecov
script:
   - mvn clean test install -P release
addons:
  coverity_scan:
    project:
      name: "ikogan/rundeck-http-plugin"
      description: "Rundeck HTTP Workflow Step Plugin"
    notification_email: kogan@ohio.edu
    build_command_prepend: "mvn clean"
    build_command:   "mvn -DskipTests=true compile"
    branch_pattern: master